---
name: AWS Cloudformation Stack Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
    upload-to-s3:
        name: Upload to S3
        runs-on: ubuntu-latest

        env:
            AWS_REGION: us-east-1
            # AWS Roles ARN
            OIDC_ROLE_ARN: ${{ secrets.CICD_ROLE_ARN }}
            # S3 buckets & Keys
            CFN_BUCKET_NAME: lame-delegation-cf-templates
            CFN_KEY: nonprod/lame-delegation-cf.yaml
            LAMBDA_FUNCTION: lame-delegation-analyzer
            LAMBDA_BUCKET: lame-delegation-code
            LAMBDA_BUCKET_KEY: 

        steps:
          - name: Checkout code
            uses: actions/checkout@v5

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v6.2.4
            with:
              role-to-assume: ${{ env.OIDC_ROLE_ARN }}
              aws-region: us-east-1

          - name: Deploy CloudFormation Stack
            uses: aws-actions/aws-cloudformation-github-deploy@v2
            with:
              name: LameDelegationStack
              template: ${{ github.workspace }}/templates/cloudformation/lame-delegation-cf.yaml
              fail-on-empty-changeset: false

          - name: Create Lambda deployment package
            run: |
              mkdir -p templates/src-zip
              zip -r templates/src-zip/src.zip src
              ls -lh templates/src-zip

          - name: Upload Lambda Deployment Package to S3
            run: |
              aws s3 cp "templates/src-zip/src.zip" \
                "s3://$LAMBDA_BUCKET"

          - name: Deploy Live Lambda Code Update
            run: |
              aws lambda update-function-code \
                --function-name $LAMBDA_FUNCTION \
                --s3-bucket $LAMBDA_BUCKET \
                --s3-key "src.zip"
